fix: add support for Saleor v3.23 (#56)
The app was using Saleor 3.20 which made it impossible to use against Saleor 3.23 due to having renamed `checkoutId` variable/input to `id`. This was fixed by renaming the field, and regenerating the GraphQL types for 3.23 instead of 3.20.

This also adds extra logging in some areas (not all of the problematic ones), which allows to gather information about why the server returns HTTP 500 - without this, it would return an useless error:

```
(0 , next_dist_client_components_redirect_js__WEBPACK_IMPORTED_MODULE_1__.isRedirectError) is not a function
```

This is likely a bug however I am not sure what to fix for this.

This also updates graphql-request to ≥ 7.4.0 in order to have the fix from https://github.com/graffle-js/graffle/commit/7a1ee760033f44fd09b1e22cfbe69b60406af8ff which allows us to see the GraphQL response (HTTP body) when receiving HTTP 400 which is critical in order to understand why the HTTP 400 is occurring (in this instance it was happening because `checkoutId` was renamed to `id` in Saleor 3.23, but doing `try { ... } catch (error) { console.error({error}); }` would not log the error message from Saleor).